// Code generated by MockGen. DO NOT EDIT.
// Source: content_builders.go
//
// Generated by this command:
//
//	mockgen -source=content_builders.go -destination=../../mocks/contentbuilders/delete_ticket_content_builder.go -package=mockcontentbuilders -exclude_interfaces=ForgetPasswordContentBuilder,UpdateTicketContentBuilder,VerifyEmailContentBuilder
//

// Package mockcontentbuilders is a generated GoMock package.
package mockcontentbuilders

import (
	reflect "reflect"

	dto "github.com/DKhorkov/hmtm-notifications/dto"
	entities "github.com/DKhorkov/hmtm-notifications/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTicketContentBuilder is a mock of DeleteTicketContentBuilder interface.
type MockDeleteTicketContentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTicketContentBuilderMockRecorder
	isgomock struct{}
}

// MockDeleteTicketContentBuilderMockRecorder is the mock recorder for MockDeleteTicketContentBuilder.
type MockDeleteTicketContentBuilderMockRecorder struct {
	mock *MockDeleteTicketContentBuilder
}

// NewMockDeleteTicketContentBuilder creates a new mock instance.
func NewMockDeleteTicketContentBuilder(ctrl *gomock.Controller) *MockDeleteTicketContentBuilder {
	mock := &MockDeleteTicketContentBuilder{ctrl: ctrl}
	mock.recorder = &MockDeleteTicketContentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTicketContentBuilder) EXPECT() *MockDeleteTicketContentBuilderMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockDeleteTicketContentBuilder) Body(ticketData dto.DeleteTicketDTO, ticketOwner, respondOwner entities.User) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body", ticketData, ticketOwner, respondOwner)
	ret0, _ := ret[0].(string)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockDeleteTicketContentBuilderMockRecorder) Body(ticketData, ticketOwner, respondOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockDeleteTicketContentBuilder)(nil).Body), ticketData, ticketOwner, respondOwner)
}

// Subject mocks base method.
func (m *MockDeleteTicketContentBuilder) Subject(ticketData dto.DeleteTicketDTO) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject", ticketData)
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockDeleteTicketContentBuilderMockRecorder) Subject(ticketData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockDeleteTicketContentBuilder)(nil).Subject), ticketData)
}
