// Code generated by MockGen. DO NOT EDIT.
// Source: content_builders.go
//
// Generated by this command:
//
//	mockgen -source=content_builders.go -destination=../../mocks/contentbuilders/ticket_updated_content_builder.go -package=mockcontentbuilders -exclude_interfaces=ForgetPasswordContentBuilder,VerifyEmailContentBuilder,TicketDeletedContentBuilder
//

// Package mockcontentbuilders is a generated GoMock package.
package mockcontentbuilders

import (
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-notifications/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketUpdatedContentBuilder is a mock of TicketUpdatedContentBuilder interface.
type MockTicketUpdatedContentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockTicketUpdatedContentBuilderMockRecorder
	isgomock struct{}
}

// MockTicketUpdatedContentBuilderMockRecorder is the mock recorder for MockTicketUpdatedContentBuilder.
type MockTicketUpdatedContentBuilderMockRecorder struct {
	mock *MockTicketUpdatedContentBuilder
}

// NewMockTicketUpdatedContentBuilder creates a new mock instance.
func NewMockTicketUpdatedContentBuilder(ctrl *gomock.Controller) *MockTicketUpdatedContentBuilder {
	mock := &MockTicketUpdatedContentBuilder{ctrl: ctrl}
	mock.recorder = &MockTicketUpdatedContentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketUpdatedContentBuilder) EXPECT() *MockTicketUpdatedContentBuilderMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockTicketUpdatedContentBuilder) Body(ticket entities.RawTicket, respondOwner entities.User) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body", ticket, respondOwner)
	ret0, _ := ret[0].(string)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockTicketUpdatedContentBuilderMockRecorder) Body(ticket, respondOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockTicketUpdatedContentBuilder)(nil).Body), ticket, respondOwner)
}

// Subject mocks base method.
func (m *MockTicketUpdatedContentBuilder) Subject(ticket entities.RawTicket) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject", ticket)
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockTicketUpdatedContentBuilderMockRecorder) Subject(ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockTicketUpdatedContentBuilder)(nil).Subject), ticket)
}
