// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/emails_repository.go -exclude_interfaces=ToysRepository,SsoRepository,TicketsRepository -package=mockrepositories
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-notifications/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailsRepository is a mock of EmailsRepository interface.
type MockEmailsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailsRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailsRepositoryMockRecorder is the mock recorder for MockEmailsRepository.
type MockEmailsRepositoryMockRecorder struct {
	mock *MockEmailsRepository
}

// NewMockEmailsRepository creates a new mock instance.
func NewMockEmailsRepository(ctrl *gomock.Controller) *MockEmailsRepository {
	mock := &MockEmailsRepository{ctrl: ctrl}
	mock.recorder = &MockEmailsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailsRepository) EXPECT() *MockEmailsRepositoryMockRecorder {
	return m.recorder
}

// GetUserCommunications mocks base method.
func (m *MockEmailsRepository) GetUserCommunications(ctx context.Context, userID uint64) ([]entities.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCommunications", ctx, userID)
	ret0, _ := ret[0].([]entities.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCommunications indicates an expected call of GetUserCommunications.
func (mr *MockEmailsRepositoryMockRecorder) GetUserCommunications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCommunications", reflect.TypeOf((*MockEmailsRepository)(nil).GetUserCommunications), ctx, userID)
}

// SaveCommunication mocks base method.
func (m *MockEmailsRepository) SaveCommunication(ctx context.Context, email entities.Email) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommunication", ctx, email)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCommunication indicates an expected call of SaveCommunication.
func (mr *MockEmailsRepositoryMockRecorder) SaveCommunication(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommunication", reflect.TypeOf((*MockEmailsRepository)(nil).SaveCommunication), ctx, email)
}
