// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/emails_repository.go -package=mockrepositories
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-notifications/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailsRepository is a mock of EmailsRepository interface.
type MockEmailsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailsRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailsRepositoryMockRecorder is the mock recorder for MockEmailsRepository.
type MockEmailsRepositoryMockRecorder struct {
	mock *MockEmailsRepository
}

// NewMockEmailsRepository creates a new mock instance.
func NewMockEmailsRepository(ctrl *gomock.Controller) *MockEmailsRepository {
	mock := &MockEmailsRepository{ctrl: ctrl}
	mock.recorder = &MockEmailsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailsRepository) EXPECT() *MockEmailsRepositoryMockRecorder {
	return m.recorder
}

// GetUserEmailCommunications mocks base method.
func (m *MockEmailsRepository) GetUserEmailCommunications(ctx context.Context, userID uint64) ([]entities.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailCommunications", ctx, userID)
	ret0, _ := ret[0].([]entities.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailCommunications indicates an expected call of GetUserEmailCommunications.
func (mr *MockEmailsRepositoryMockRecorder) GetUserEmailCommunications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailCommunications", reflect.TypeOf((*MockEmailsRepository)(nil).GetUserEmailCommunications), ctx, userID)
}
